# 이 프로젝트 실행시키고 localhost:8888/ecommerce/default 로 들어가면 된다.
server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:\\\C:\MicroService-SpringCloudConfigServerLocalGit # ecommerce.yml 파일이 저장된 파일 경로 지정 (file:// 은 파일 프로토콜을 사용하겠다는 의미이다.)
